export const CURRICULUM = [
  {
    id: "1",
    subject: "البرمجة كائنية التوجه OOP",
    weeks: [
      {
        weekId: 1,
        week: "الأسبوع الأول",
        resources: [
          {
            id: 101,
            type: "ملف",
            title: "Lecture - 1",
            fileType: "pdf",
            status: false,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/lecture1.pdf",
          },
          {
            id: 102,
            type: "ملف",
            title: "Section - 1",
            fileType: "pdf",
            status: true,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/section1.pdf",
          },
          {
            id: 103,
            type: "فيديو",
            title: "Lecture - 1 Video",
            fileType: "video",
            status: false,
            actions: {
              play: true,
              download: true,
            },
            url: "/materials/lecture1.mp4",
          },
          {
            id: 104,
            type: "ملف",
            title: "Assignment - 1",
            fileType: "pdf",
            status: true,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/assignment1.pdf",
          },
          {
            id: 105,
            type: "ملف",
            title: "Quiz - 1",
            fileType: "pdf",
            status: true,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/quiz1.pdf",
          },
        ],
      },
      {
        weekId: 2,
        week: "الأسبوع الثاني",
        resources: [
          {
            id: 201,
            type: "ملف",
            title: "Lecture - 2",
            fileType: "pdf",
            status: false,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/lecture2.pdf",
          },
          {
            id: 202,
            type: "ملف",
            title: "Section - 2",
            fileType: "pdf",
            status: true,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/section2.pdf",
          },
          {
            id: 203,
            type: "فيديو",
            title: "Lecture - 2 Video",
            fileType: "video",
            status: false,
            actions: {
              play: true,
              download: true,
            },
            url: "/materials/lecture2.mp4",
          },
          {
            id: 204,
            type: "ملف",
            title: "Assignment - 2",
            fileType: "pdf",
            status: true,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/assignment2.pdf",
          },
          {
            id: 205,
            type: "ملف",
            title: "Quiz - 2",
            fileType: "pdf",
            status: true,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/quiz2.pdf",
          },
        ],
      },
      {
        weekId: 3,
        week: "الأسبوع الثالث",
        resources: [
          {
            id: 301,
            type: "ملف",
            title: "Lecture - 3",
            fileType: "pdf",
            status: false,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/lecture3.pdf",
          },
          {
            id: 302,
            type: "ملف",
            title: "Section - 3",
            fileType: "pdf",
            status: true,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/section3.pdf",
          },
          {
            id: 303,
            type: "فيديو",
            title: "Lecture - 3 Video",
            fileType: "video",
            status: false,
            actions: {
              play: true,
              download: true,
            },
            url: "/materials/lecture3.mp4",
          },
          {
            id: 304,
            type: "ملف",
            title: "Assignment - 3",
            fileType: "pdf",
            status: true,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/assignment3.pdf",
          },
          {
            id: 305,
            type: "ملف",
            title: "Quiz - 3",
            fileType: "pdf",
            status: true,
            actions: {
              open: true,
              download: true,
            },
            url: "/materials/quiz3.pdf",
          },
        ],
      },
    ],
  },
];
