import TasksCards from "./TasksCards";

const subjectData = [
  {
    id: 1,
    name: "OOP Course 1",
    subjectName: 'البرمجة كائنية التوجه "OOP"',
    doctorName: "د. أحمد المنوفي",
    cardButtonName: "رؤية المهام",
    assignments: [
      {
        id: 1,
        parameters: "صمم تسلسل هرمي للفئات لنظام مصرفي",
        returnValues: "مخططات الفئات وعينة من الشيفرة",
        createdAt: new Date("2025-03-01T10:00:00"),
        updatedAt: new Date("2025-03-01T10:00:00"),
        finished: true,
        published: true,
      },
      {
        id: 2,
        parameters: "قم بتنفيذ الوراثة باستخدام فئة المركبات",
        returnValues: "كود وظيفي وحالات اختبار",
        createdAt: new Date("2025-03-02T14:00:00"),
        updatedAt: new Date("2025-03-02T14:00:00"),
        finished: false,
        published: false,
      },
      {
        id: 3,
        parameters: "قم بإنشاء برنامج محاكاة لنظام حجوزات الطيران",
        returnValues: "كود المحاكاة وتقرير المخرجات",
        createdAt: new Date("2025-03-03T16:00:00"),
        updatedAt: new Date("2025-03-03T16:00:00"),
        finished: false,
        published: true,
      },
    ],
  },
  {
    id: 2,
    name: "OOP Course 2",
    subjectName: 'البرمجة كائنية التوجه "OOP"',
    doctorName: "د. أحمد المنوفي",
    cardButtonName: "رؤية المهام",
    assignments: [
      {
        id: 4,
        parameters: "أنشئ مثالاً عن تعدد الأشكال باستخدام الأشكال الهندسية",
        returnValues: "كود وعرض للمخرجات",
        createdAt: new Date("2025-03-03T09:00:00"),
        updatedAt: new Date("2025-03-03T09:00:00"),
        finished: true,
        published: true,
      },
      {
        id: 5,
        parameters: "طور تمرينًا عن التغليف (Encapsulation)",
        returnValues: "كود يحتوي على سمات خاصة ووسائل وصول (Getters/Setters)",
        createdAt: new Date("2025-03-04T11:00:00"),
        updatedAt: new Date("2025-03-04T11:00:00"),
        finished: false,
        published: false,
      },
      {
        id: 6,
        parameters: "صمم نظام إدارة مكتبة باستخدام قواعد البيانات",
        returnValues: "مخططات قاعدة البيانات والكود",
        createdAt: new Date("2025-03-05T13:00:00"),
        updatedAt: new Date("2025-03-05T13:00:00"),
        finished: false,
        published: true,
      },
    ],
  },
  {
    id: 3,
    name: "OOP Course 3",
    subjectName: 'البرمجة كائنية التوجه "OOP"',
    doctorName: "د. أحمد المنوفي",
    cardButtonName: "رؤية المهام",
    assignments: [
      {
        id: 7,
        parameters: "قم بإنشاء فئة مجردة لشخصية لعبة",
        returnValues: "فئة مجردة وفئات مشتقة",
        createdAt: new Date("2025-03-05T13:00:00"),
        updatedAt: new Date("2025-03-05T13:00:00"),
        finished: false,
        published: false,
      },
      {
        id: 8,
        parameters: "قم بتنفيذ واجهات لنظام مكتبة",
        returnValues: "تعريفات الواجهة والتنفيذ",
        createdAt: new Date("2025-03-06T15:00:00"),
        updatedAt: new Date("2025-03-06T15:00:00"),
        finished: true,
        published: true,
      },
      {
        id: 9,
        parameters: "إنشاء نظام تسجيل دخول باستخدام التشفير",
        returnValues: "كود التشفير وآلية المصادقة",
        createdAt: new Date("2025-03-07T17:00:00"),
        updatedAt: new Date("2025-03-07T17:00:00"),
        finished: false,
        published: true,
      },
    ],
  },
  {
    id: 4,
    name: "OOP Course 1",
    subjectName: 'البرمجة كائنية التوجه "OOP"',
    doctorName: "د. أحمد المنوفي",
    cardButtonName: "رؤية المهام",
    assignments: [
      {
        id: 10,
        parameters: "صمم تسلسل هرمي للفئات لنظام مصرفي",
        returnValues: "مخططات الفئات وعينة من الشيفرة",
        createdAt: new Date("2025-03-01T10:00:00"),
        updatedAt: new Date("2025-03-01T10:00:00"),
        finished: true,
        published: true,
      },
      {
        id: 11,
        parameters: "قم بتنفيذ الوراثة باستخدام فئة المركبات",
        returnValues: "كود وظيفي وحالات اختبار",
        createdAt: new Date("2025-03-02T14:00:00"),
        updatedAt: new Date("2025-03-02T14:00:00"),
        finished: false,
        published: false,
      },
      {
        id: 12,
        parameters: "قم بإنشاء برنامج محاكاة لنظام حجوزات الطيران",
        returnValues: "كود المحاكاة وتقرير المخرجات",
        createdAt: new Date("2025-03-03T16:00:00"),
        updatedAt: new Date("2025-03-03T16:00:00"),
        finished: false,
        published: true,
      },
    ],
  },
  {
    id: 5,
    name: "OOP Course 2",
    subjectName: 'البرمجة كائنية التوجه "OOP"',
    doctorName: "د. أحمد المنوفي",
    cardButtonName: "رؤية المهام",
    assignments: [
      {
        id: 13,
        parameters: "أنشئ مثالاً عن تعدد الأشكال باستخدام الأشكال الهندسية",
        returnValues: "كود وعرض للمخرجات",
        createdAt: new Date("2025-03-03T09:00:00"),
        updatedAt: new Date("2025-03-03T09:00:00"),
        finished: false,
        published: true,
      },
      {
        id: 14,
        parameters: "طور تمرينًا عن التغليف (Encapsulation)",
        returnValues: "كود يحتوي على سمات خاصة ووسائل وصول (Getters/Setters)",
        createdAt: new Date("2025-03-04T11:00:00"),
        updatedAt: new Date("2025-03-04T11:00:00"),
        finished: false,
        published: false,
      },
      {
        id: 15,
        parameters: "صمم نظام إدارة مكتبة باستخدام قواعد البيانات",
        returnValues: "مخططات قاعدة البيانات والكود",
        createdAt: new Date("2025-03-05T13:00:00"),
        updatedAt: new Date("2025-03-05T13:00:00"),
        finished: false,
        published: false,
      },
    ],
  },
  {
    id: 6,
    name: "OOP Course 3",
    subjectName: 'البرمجة كائنية التوجه "OOP"',
    doctorName: "د. أحمد المنوفي",
    cardButtonName: "رؤية المهام",
    assignments: [
      {
        id: 16,
        parameters: "قم بإنشاء فئة مجردة لشخصية لعبة",
        returnValues: "فئة مجردة وفئات مشتقة",
        createdAt: new Date("2025-03-05T13:00:00"),
        updatedAt: new Date("2025-03-05T13:00:00"),
        finished: false,
        published: false,
      },
      {
        id: 17,
        parameters: "قم بتنفيذ واجهات لنظام مكتبة",
        returnValues: "تعريفات الواجهة والتنفيذ",
        createdAt: new Date("2025-03-06T15:00:00"),
        updatedAt: new Date("2025-03-06T15:00:00"),
        finished: true,
        published: true,
      },
      {
        id: 18,
        parameters: "إنشاء نظام تسجيل دخول باستخدام التشفير",
        returnValues: "كود التشفير وآلية المصادقة",
        createdAt: new Date("2025-03-07T17:00:00"),
        updatedAt: new Date("2025-03-07T17:00:00"),
        finished: false,
        published: true,
      },
    ],
  },
];
function TasksContent() {
  return <TasksCards tasksData={subjectData} />;
}

export default TasksContent;
