export const days = [
    "كل الأيام",
    "السبت",
    "الأحد",
    "الإثنين",
    "الثلاثاء",
    "الأربعاء",
    "الخميس",
];

export const schedules = [
    {
        id: 1,
        day: "السبت",
        course: "Data Structures",
        time: "10:12",
        type: "محاضرة",
        teacher: "د. محمد عبد الرحمن",
        place: "مدرج 3",
        status: "في موعدها",
    },
    {
        id: 2,
        day: "السبت",
        course: "Algorithms",
        time: "12:2",
        type: "سكشن",
        teacher: "م. خالد السعدي",
        place: "معمل 205",
        status: "تم التأجيل",
    },
    {
        id: 3,
        day: "السبت",
        course: "Computer Networks",
        time: "3:5",
        type: "محاضرة",
        teacher: "أ.د أحمد زكريا",
        place: "مدرج 1",
        status: "تم الالغاء",
    },
    {
        id: 4,
        day: "الأحد",
        course: "Operating Systems",
        time: "9:11",
        type: "سكشن",
        teacher: "د. سعاد محسن",
        place: "معمل 108",
        status: "في موعدها",
    },
    {
        id: 5,
        day: "الأحد",
        course: "Artificial Intelligence",
        time: "2:4",
        type: "محاضرة",
        teacher: "أ.د محمود العطار",
        place: "مدرج 5",
        status: "تم التأجيل",
    },
    {
        id: 6,
        day: "الإثنين",
        course: "Software Engineering",
        time: "10:12",
        type: "محاضرة",
        teacher: "م. ياسر الدسوقي",
        place: "مدرج 6",
        status: "تم الالغاء",
    },
    {
        id: 7,
        day: "الإثنين",
        course: "Cyber Security",
        time: "1:3",
        type: "سكشن",
        teacher: "د. ليلى فاروق",
        place: "معمل 210",
        status: "في موعدها",
    },
    {
        id: 8,
        day: "الثلاثاء",
        course: "Database Management",
        time: "9:11",
        type: "محاضرة",
        teacher: "أ.د خالد الشريف",
        place: "مدرج 4",
        status: "تم التأجيل",
    },
    {
        id: 9,
        day: "الثلاثاء",
        course: "Machine Learning",
        time: "12:2",
        type: "سكشن",
        teacher: "م. رامي عبد الكريم",
        place: "معمل 301",
        status: "في موعدها",
    },
    {
        id: 10,
        day: "الأربعاء",
        course: "Computer Vision",
        time: "11:1",
        type: "محاضرة",
        teacher: "د. حسن أبو النور",
        place: "مدرج 2",
        status: "تم الالغاء",
    },
    {
        id: 11,
        day: "الأربعاء",
        course: "Cloud Computing",
        time: "3:5",
        type: "سكشن",
        teacher: "م. هالة الديب",
        place: "معمل 215",
        status: "في موعدها",
    },
    {
        id: 12,
        day: "الخميس",
        course: "Parallel Computing",
        time: "9:11",
        type: "محاضرة",
        teacher: "أ.د سامي النجار",
        place: "مدرج 7",
        status: "تم التأجيل",
    },
    {
        id: 13,
        day: "الخميس",
        course: "Embedded Systems",
        time: "1:3",
        type: "سكشن",
        teacher: "د. مصطفى حمدي",
        place: "معمل 402",
        status: "في موعدها",
    },
];
